image: node:20.10.0

cache:
  paths:
    - node_modules/
    - dist/

before_script:
  - apt-get update -qy
  - apt-get install -y curl
  - curl -sL https://deb.nodesource.com/setup_14.x | bash -
  - apt-get install -y nodejs
  - npm install -g npm@latest
  - npm install

stages:
  - build
  - staging
  - production

build:
  stage: build
  script:
    - npm run build

staging:
  stage: staging
  image: node:20.10.0
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - staging

production:
  stage: production
  image: node:20.10.0
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master


 